spring:
  server:
    port: 8080
  datasource:
    url: ${DEMO_POSTGRESQL_URL:jdbc:postgresql://localhost:5432/project}
    username: ${DEMO_POSTGRESQL_USERNAME:postgres}
    password: ${DEMO_POSTGRESQL_PASSWORD:qwer1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        characterEncoding: UTF-8
    show-sql: true
    hibernate:
      ddl-auto: none
    flyway:
      enabled: true
      baseline-on-migrate: true
      locations:
        - classpath:db/migration