spring:
  datasource:
    url: ${DEMO_POSTGRESQL_URL:jdbc:postgresql://localhost:5432/project}  # 환경 변수를 사용하여 URL 설정
    username: ${DEMO_POSTGRESQL_USERNAME:postgres}  # 환경 변수로 사용자 이름 설정
    password: ${DEMO_POSTGRESQL_PASSWORD:qwer1234}  # 환경 변수로 비밀번호 설정
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        characterEncoding: UTF-8
    show-sql: true # profile 설정 안 해도 확인할 수 있도록 임시로 true 함.
    hibernate:
      ddl-auto: none # flyway 사용하면 none 또는 validate (엄격한 경우 validate)

    flyway:
      enabled: true
      baseline-on-migrate: true # flyway schema history 테이블이 없다면 생성한다.
      locations:
        - classpath:db/migration