spring:
  server:
    port: 8080
  datasource:
    url: ${DEMO_POSTGRESQL_URL:jdbc:postgresql://localhost:5432/project}
    username: ${DEMO_POSTGRESQL_USERNAME:postgres}
    password: ${DEMO_POSTGRESQL_PASSWORD:qwer1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        characterEncoding: UTF-8
    show-sql: true
    hibernate:
      ddl-auto: none
    flyway:
      enabled: true
      baseline-on-migrate: true
      locations:
        - classpath:db/migration
jwt:
  secret: https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c# 실제 사용할 시, 강력한 비밀 키 사용
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000